manipulator_i5:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.01  # 增加搜索分辨率
  kinematics_solver_timeout: 0.1  # 增加超时时间
  kinematics_solver_attempts: 5  # 增加尝试次数
